maxnowack/signaldb

__tests__/Reactivity.spec.ts
docs/.vitepress/config.ts
docs/reactivity/reactively.md
package-lock.json
package.json

feat: add docs and tests for reactivity with reactively

---

__tests__/Reactivity.spec.ts
docs/.vitepress/config.ts
docs/reactivity/S.md
package-lock.json
package.json

feat: add docs and tests for reactivity with S.js

---

.github/workflows/checks.yaml

ci: build docs for each pull request

---

.github/workflows/checks.yaml

Reverts maxnowack/signaldb#158

Revert "chore(deps): update codecov/codecov-action action to v4"

---

example/src/utils/createRxPersistenceAdapter.ts
src/Collection/index.ts

this is needed as all existing items will be overwritten on load

fix: discard loading persistent items if there is a ongoing save

---

__tests__/Reactivity.spec.ts
docs/.vitepress/config.mts
docs/reactivity/index.md
docs/reactivity/vue/index.md
package-lock.json
package.json

feat: implement reactivity adapter for vue.js

---

.eslintrc.js
.github/workflows/checks.yaml
.github/workflows/deploy-docs.yaml
docs/.vitepress/config.mts
docs/data-persistence/appwrite/index.md
docs/replication/index.md
examples/appwrite/.gitignore
examples/appwrite/README.md
examples/appwrite/next.config.js
examples/appwrite/package-lock.json
examples/appwrite/package.json
examples/appwrite/src/app/globals.scss
examples/appwrite/src/app/layout.tsx
examples/appwrite/src/app/page.tsx
examples/appwrite/src/containers/App/List.tsx
examples/appwrite/src/containers/App/index.tsx
examples/appwrite/src/system/setupCollection/index.ts
examples/appwrite/src/system/setupCollection/persistence.ts
examples/appwrite/src/system/setupCollection/reactivity.ts
examples/appwrite/src/utils/createAppwritePersistenceAdapter.ts
examples/appwrite/tsconfig.json
package.json

docs: add appwrite example and persistence adapter

---

.github/workflows/checks.yaml
.github/workflows/deploy-docs.yaml
docs/.vitepress/config.mts
docs/data-persistence/supabase/index.md
examples/supabase/.gitignore
examples/supabase/README.md
examples/supabase/next.config.js
examples/supabase/package-lock.json
examples/supabase/package.json
examples/supabase/src/app/globals.scss
examples/supabase/src/app/layout.tsx
examples/supabase/src/app/page.tsx
examples/supabase/src/containers/App/List.tsx
examples/supabase/src/containers/App/index.tsx
examples/supabase/src/system/setupCollection/index.ts
examples/supabase/src/system/setupCollection/persistence.ts
examples/supabase/src/system/setupCollection/reactivity.ts
examples/supabase/src/utils/createSupabasePersistenceAdapter.ts
examples/supabase/tsconfig.json
package.json

docs: add supabase example and persistence adapter

---

package-lock.json
package.json
vite.config.ts

chore: upgrade to vitest v1

---

.gitignore
packages/signaldb/__tests__/PersistentCollection.client.spec.ts
packages/signaldb/__tests__/PersistentCollection.spec.ts
packages/signaldb/__tests__/persistence.client.spec.ts
packages/signaldb/__tests__/persistence.spec.ts
packages/signaldb/src/Collection/index.ts
packages/signaldb/src/persistence/createFilesystemAdapter.ts
packages/signaldb/src/persistence/createLocalStorageAdapter.ts
packages/signaldb/src/types/PersistenceAdapter.ts

fix: don't discard data modified before persistence.init

---

docs/.vitepress/config.mts
docs/guides/index.md
docs/guides/react/index.md
docs/integrations/index.md
docs/integrations/react/index.md
package-lock.json
packages/react/__tests__/useReactivity.spec.ts
packages/react/package.json
packages/react/src/index.ts
packages/react/tsconfig.json
packages/react/vite.config.ts

feat: add package for creating useReactivity react hook

---

packages/signaldb/__tests__/Collection.spec.ts
packages/signaldb/src/Collection/index.ts

fix: remove id from index after removal

---

packages/signaldb/__tests__/persistence.spec.ts
packages/signaldb/src/Collection/index.ts

fix: upsert items that are added but already present

---

packages/signaldb/__tests__/reactivity.spec.ts
packages/signaldb/src/Collection/index.ts
packages/signaldb/src/utils/deepClone.spec.ts
packages/signaldb/src/utils/deepClone.ts

fix: deep clone items on update operations

---

packages/signaldb/__tests__/AutoFetchCollection.spec.ts
packages/signaldb/src/AutoFetchCollection.ts

this enables returning different fields for items in different queries and merging them afterwards

feat: keep track of results of different fetchQueryItems calls in AutoFetchCollection

---

packages/signaldb/src/types/EventEmitter.ts

fix: simplify typed EventEmitter

---

packages/signaldb/src/persistence/createFilesystemAdapter.ts
packages/signaldb/src/persistence/createLocalStorageAdapter.ts
packages/signaldb/src/persistence/createOPFSAdapter.ts

feat: allow using custom serialization in default persistence adapters

---

docs/reactivity/index.md
docs/reactivity/vue/index.md
packages/plugin-vue/__tests__/reactivity.spec.ts
packages/plugin-vue/src/index.ts

feat: implement automatic scope checking for vue

---

docs/.vitepress/config.mts
docs/sync/implementation/index.md
docs/sync/index.md
docs/sync/reference/index.md
package-lock.json
package.json
packages/signaldb/__tests__/sync/SyncManager.spec.ts
packages/signaldb/__tests__/sync/applyChanges.spec.ts
packages/signaldb/__tests__/sync/computeChanges.spec.ts
packages/signaldb/__tests__/sync/getSnapshot.spec.ts
packages/signaldb/__tests__/sync/sync.spec.ts
packages/signaldb/src/SyncManager/applyChanges.ts
packages/signaldb/src/SyncManager/computeChanges.ts
packages/signaldb/src/SyncManager/getSnapshot.ts
packages/signaldb/src/SyncManager/index.ts
packages/signaldb/src/SyncManager/sync.ts
packages/signaldb/src/SyncManager/types.ts
packages/signaldb/src/index.ts
packages/signaldb/src/utils/PromiseQueue.spec.ts
packages/signaldb/src/utils/PromiseQueue.ts
packages/signaldb/src/utils/debounce.spec.ts
packages/signaldb/src/utils/debounce.ts

Work in progress. I will update this PR soon with an explanation how the `SyncManager` works and how to use it.
I'm really unsure about the naming and I'm happy to get some feedback on this.
Right now the SyncManager is placed in the `signaldb` package, but I plan to move it to it's own package later on (probably `v1.0.0`).
I would love to get feedback in general on this. Maybe someone has the time to take a quick look at it 🙂 
I've already added [some tests](https://github.com/maxnowack/signaldb/blob/sync/packages/signaldb/src/SyncManager/index.ts), so this might be a good starting point.

feat: implement sync manager

---

docs/sync/implementation/index.md

Several spelling and sentence changes

Update Sync Manager Docs

---

docs/collections/index.md
packages/signaldb/__tests__/Collection.spec.ts
packages/signaldb/src/Collection/index.ts

Hello Max,
I added the small method and did a small test about it. I didn't add any new event in order to avoid polluting the bus.
What do you think?

feat: add insertMany to Collection (leveraging on batch method)

---

packages/plugin-solid/src/index.ts

fixes #938
Tested it in [obedm503/trellix-offline](https://github.com/obedm503/trellix-offline) and everything appears to be working.

feat: add solid reactivity scope checking

---

packages/signaldb/__tests__/helpers/memoryPersistenceAdapter.ts
packages/signaldb/__tests__/persistence.spec.ts
packages/signaldb/__tests__/sync/SyncManager.spec.ts
packages/signaldb/__tests__/sync/applyChanges.spec.ts
packages/signaldb/src/SyncManager/applyChanges.ts
packages/signaldb/src/SyncManager/index.ts

fix(sync): wait until persistence adapters ready before first sync

---

packages/signaldb/__tests__/sync/SyncManager.spec.ts
packages/signaldb/src/SyncManager/index.ts

BREAKING CHANGE: onError now takes the collectionOptions as first parameter instead of the error.
The error is passed as the second parameter

fix: call onError on every error that is thrown during sync

---

docs/data-persistence/other/index.md

Move type information into code blocks so it's easier to read with colorizing.
Clarify that save() aways gets items and changes and can chose which one to use.

Further clarify createCustomAdapter documentation

---

packages/signaldb/src/Collection/index.ts

Only call memoryArray once

---

packages/signaldb/vite.config.ts

chore(build): turn on preserveModules

---

examples/appwrite/package.json
examples/firebase/package.json
examples/replication-http/package.json
examples/rxdb/package.json
examples/supabase/package.json
package.json

Reverts maxnowack/signaldb#1148

Revert "chore(deps): update dependency typescript to v5.7.2"

---

examples/appwrite/package.json
examples/firebase/package.json
examples/replication-http/package.json
examples/rxdb/package.json
examples/supabase/package.json
package-lock.json
package.json
packages/react/__tests__/useReactivity.spec.ts
packages/react/package.json

chore: fix update to react v19

---

packages/signaldb/package.json

fix: commonjs build

---

docs/devtools/index.md
packages/base/core/CHANGELOG.md
packages/base/core/src/index.ts

resolves https://github.com/maxnowack/signaldb/issues/1292

Devtools production

---

docs/reference/sync/index.md
packages/base/sync/__tests__/SyncManager.spec.ts
packages/base/sync/src/SyncManager.ts

I've rebased #951 and implement the requested changes.
@obedm503 I hope that's okay for you. I left your name in the commit so you can get the credit.
closes #951

feat(sync-manager): implement sync pause and resume

---

packages/base/core/src/devtools.ts

fix: resolve issue with unresolved devtools package in angular

---

eslint.config.mjs
packages/base/core/CHANGELOG.md
packages/base/core/src/devtools.ts

fix: check if @signaldb/devtools is available

---

packages/base/sync/__tests__/SyncManager.spec.ts
packages/base/sync/src/SyncManager.ts

fixes #1470 
also added a debounceTime parameter to the SyncManager constructor, so the debounce can be configured.

fix(sync): per-collection sync debounce

---

docs/guides/svelte/index.md

docs: update svelte guide to recover reactivity with svelte@5.24.0

---

packages/base/core/CHANGELOG.md
packages/base/core/src/AutoFetchCollection.ts
packages/base/core/src/Collection/index.ts
packages/base/core/src/ReplicatedCollection.ts
packages/base/core/src/utils/createSignal.spec.ts
packages/base/core/src/utils/createSignal.ts

fix: add missing scope check for internal signals

---

docs/guides/svelte/index.md

docs: fix svelte guide

---

packages/reactivity-adapters/svelte/CHANGELOG.md
packages/reactivity-adapters/svelte/index.svelte.ts

fix(svelte): guard stop call in reactivity adapter to prevent errors

---

packages/reactivity-adapters/svelte/__tests__/reactivity.svelte.spec.ts
packages/reactivity-adapters/svelte/index.svelte.ts

related: https://github.com/maxnowack/signaldb/issues/1566
Hi! 👋
I felt that the implementation of svelteReactivityAdapter was getting a bit complex, so I refactored it into a separate class. I’ve also added tests for the newly created class.

fix(svelte): refactor and add tests

---

packages/reactivity-adapters/svelte/CHANGELOG.md
packages/reactivity-adapters/svelte/__tests__/reactivity.svelte.spec.ts
packages/reactivity-adapters/svelte/index.svelte.ts

related: https://github.com/maxnowack/signaldb/issues/1566
Sorry for splitting this up, but this is an additional fix for https://github.com/maxnowack/signaldb/pull/1601.

chore(svelte): fix svelte compiler warnings and add comments

---

packages/persistence-adapters/fs/CHANGELOG.md
packages/persistence-adapters/fs/src/index.ts
packages/persistence-adapters/localstorage/CHANGELOG.md
packages/persistence-adapters/localstorage/src/index.ts
packages/persistence-adapters/opfs/CHANGELOG.md
packages/persistence-adapters/opfs/src/index.ts

resolves https://github.com/maxnowack/signaldb/issues/1631

fix: avoid duplicate ids and unnecessary errors

---

docs/reference/core/collection/index.md
packages/base/core/CHANGELOG.md
packages/base/core/__tests__/Collection.spec.ts
packages/base/core/src/Collection/index.ts

New feature! Custom generator for primary key.

feat: custom primary key generator

---

packages/base/core/CHANGELOG.md
packages/base/core/src/index.ts

resolves https://github.com/maxnowack/signaldb/issues/1721

fix: export cursor type

---

docs/.vitepress/config.mts
package-lock.json
package.json

docs: add vitepress-plugin-llms
